import os
import json
import subprocess
import re
import getpass
import platform
import posixpath
import shlex
import shutil
from fastapi import APIRouter, Request
from cms_core.security import atomic_write_json, safe_join, validate_git_branch

router = APIRouter()

CURRENT_API_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(CURRENT_API_DIR, "..", ".."))
SOURCE_ROOT = os.path.realpath(PROJECT_ROOT)
CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "deploy_config.json")


def npm_cmd() -> str:
    return "npm.cmd" if os.name == "nt" else "npm"


@router.get("/config")
async def get_deploy_config():
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    # 🌟 默认返回双轨结构
    return {
        "blogPath": "",
        "staticRepoUrl": "",
        "staticBranch": "gh-pages",
        "sourceRepoUrl": "",
        "sourceBranch": "main"
    }


@router.post("/config")
async def save_deploy_config(request: Request):
    try:
        data = await request.json()
        os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
        atomic_write_json(CONFIG_FILE, data)
        return {"success": True, "message": "✅ 双轨部署配置已永久保存！"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


# 🔑 核心大升级：根据 type 动态获取/生成不同的 SSH 密匙，并自动配置路由！
@router.get("/ssh/key")
async def get_my_ssh_key(type: str = "static"):
    """获取或生成本地 SSH 公钥 (支持 A/B 双线隔离)"""
    try:
        ssh_dir = os.path.expanduser("~/.ssh")
        os.makedirs(ssh_dir, exist_ok=True)

        # 判断是为 A线(static) 还是 B线(source) 打钥匙
        if type == "source":
            key_name = "id_ed25519_source"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Source"
        else:
            key_name = "id_ed25519"
            user_tag = f"{getpass.getuser()}@{platform.node()}-Static"

        pub_key_path = os.path.join(ssh_dir, f"{key_name}.pub")
        priv_key_path = os.path.join(ssh_dir, key_name)

        # 兼容老用户：如果是 A 线，优先看看有没有老的 id_rsa
        if type == "static" and not os.path.exists(pub_key_path):
            if os.path.exists(os.path.join(ssh_dir, "id_rsa.pub")):
                pub_key_path = os.path.join(ssh_dir, "id_rsa.pub")

        # 如果连指定的钥匙都没有，当场打一把新的！
        if not os.path.exists(pub_key_path):
            subprocess.run([
                "ssh-keygen", "-t", "ed25519",
                "-C", user_tag,
                "-N", "",
                "-f", priv_key_path
            ], check=True)
            pub_key_path = f"{priv_key_path}.pub"

        # 🌟 极客魔法：如果是 B 线(source)，自动在本地注入 SSH 路由分流规则！
        if type == "source":
            config_path = os.path.join(ssh_dir, "config")
            # 兼容 Windows 和 Mac 路径分隔符
            safe_priv_path = priv_key_path.replace('\\', '/')
            config_entry = f"\n# Auto-generated by Blog CMS for Vercel Source Sync\nHost github-source\n    HostName github.com\n    User git\n    IdentityFile {safe_priv_path}\n"

            config_exists = False
            if os.path.exists(config_path):
                with open(config_path, "r", encoding="utf-8") as f:
                    if "Host github-source" in f.read():
                        config_exists = True

            if not config_exists:
                with open(config_path, "a", encoding="utf-8") as f:
                    f.write(config_entry)

        # 读取公钥内容并返回给前端
        with open(pub_key_path, "r", encoding="utf-8") as f:
            key_content = f.read().strip()
            return {"success": True, "key": key_content}

    except Exception as e:
        return {"success": False, "message": f"获取 SSH 失败: {str(e)}"}


@router.post("/check")
async def check_git_env(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地物理路径不存在，请先检查路径！"}

        git_dir = os.path.join(blog_path, ".git")
        if not os.path.exists(git_dir):
            return {"success": False, "message": "该路径未初始化 Git 仓库，请点击下方【一键初始化】按钮。"}

        return {"success": True, "message": "✅ Git 环境正常！已准备就绪。"}
    except Exception as e:
        return {"success": False, "message": f"Git 检测失败: {str(e)}"}


@router.post("/init")
async def init_deploy_env(request: Request):
    """初始化双轨部署环境"""
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()
        static_repo = payload.get("staticRepoUrl", "").strip()

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "目标博客路径不存在！"}

        # 1. 基础 Git 初始化
        subprocess.run(["git", "init"], cwd=blog_path, check=True)

        # 为了兼容老版的静态部署插件，我们把 origin 绑定给 A线 (静态仓库)
        if static_repo:
            subprocess.run(["git", "remote", "remove", "origin"], cwd=blog_path, stderr=subprocess.DEVNULL)
            subprocess.run(["git", "remote", "add", "origin", static_repo], cwd=blog_path, check=True)

        # 2. 修改 package.json 写入 scripts (专供 A 线静态发布)
        pkg_path = os.path.join(blog_path, "package.json")
        if os.path.exists(pkg_path):
            with open(pkg_path, "r", encoding="utf-8") as f:
                pkg_data = json.load(f)
            if "scripts" not in pkg_data:
                pkg_data["scripts"] = {}
            pkg_data["scripts"]["deploy"] = "next build && gh-pages -d out"
            with open(pkg_path, "w", encoding="utf-8") as f:
                atomic_write_json(pkg_path, pkg_data)

        # 3. 安装 gh-pages 插件
        process = subprocess.Popen(
            [npm_cmd(), "install", "gh-pages", "--save-dev"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()

        return {"success": True, "message": "✨ 太棒了！双轨部署底层依赖与配置初始化完成！"}
    except Exception as e:
        return {"success": False, "message": f"初始化发生异常: {str(e)}"}


# 🚀 A 线接口：打包静态文件并发布到 GitHub Pages
@router.post("/publish")
async def publish_to_github_pages(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        process = subprocess.Popen(
            [npm_cmd(), "run", "deploy"],
            cwd=blog_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding='utf-8'
        )
        stdout, stderr = process.communicate()
        if process.returncode == 0:
            return {"success": True, "message": "🎉 A线: 网页已成功编译并发布到静态仓库！"}
        else:
            return {"success": False, "message": f"发布失败，报错:\n{stderr}"}
    except Exception as e:
        return {"success": False, "message": f"静态发布引擎崩溃: {str(e)}"}


# ☁️ B 线接口：同步源代码到 Vercel 仓库 (全新核心功能)
# ☁️ B 线接口：同步源代码到 Vercel 仓库 (全新终极强绑定机制)
@router.post("/source")
async def sync_source_to_vercel(request: Request):
    try:
        payload = await request.json()
        blog_path = payload.get("blogPath", "").strip()

        # 读取配置
        if not os.path.exists(CONFIG_FILE):
            return {"success": False, "message": "未找到配置文件，请先点击保存！"}

        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            config = json.load(f)

        source_repo = config.get("sourceRepoUrl", "").strip()
        source_branch = validate_git_branch(config.get("sourceBranch", "main"))

        if not source_repo:
            return {"success": False, "message": "B 线源码仓库地址为空，无法同步！"}

        subprocess.run(["git", "add", "."], cwd=blog_path, check=True)

        # 1. 添加所有代码改动
        # 2. 提交代码 (这里加入容错)
        subprocess.run(
            ["git", "commit", "-m", "Auto sync source code for Vercel"],
            cwd=blog_path,
            capture_output=True,
            text=True,
            encoding="utf-8",
        )

        # 🌟 终极杀招：强行绑定 B 线专属私钥，无视 Windows 智障路由！
        ssh_dir = os.path.expanduser("~/.ssh")
        # 把 Windows 的反斜杠强制替换为正斜杠，防止 Git 识别错误
        priv_key_path = os.path.join(ssh_dir, "id_ed25519_source").replace("\\", "/")

        # 组装环境变量，用 GIT_SSH_COMMAND 强行逼迫 Git 使用这把钥匙
        custom_env = os.environ.copy()
        custom_env["GIT_SSH_COMMAND"] = f'ssh -i "{priv_key_path}" -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new'

        # 3. 推送 (携带我们强行塞进去的钥匙环境变量)
        push_process = subprocess.run(
            ["git", "push", "--", source_repo, f"HEAD:{source_branch}"],
            cwd=blog_path,
            capture_output=True,
            text=True,
            encoding='utf-8',
            env=custom_env  # 👈 就是这里！把钥匙按在 Git 脸上！
        )

        # 判断是否成功
        if push_process.returncode != 0 and "Everything up-to-date" not in push_process.stderr:
            return {"success": False, "message": f"源码同步失败:\n{push_process.stderr}"}

        return {"success": True, "message": "☁️ B线: 源码已成功送达 GitHub，Vercel 构建已触发！"}

    except Exception as e:
        return {"success": False, "message": f"源码同步引擎异常: {str(e)}"}


# ================================================================
# 🖥️ C 线：一键同步到自建云服务器 (Docker 部署)
# ================================================================

VPS_CONFIG_FILE = os.path.join(PROJECT_ROOT, "data", "vps_config.json")

SYNC_CONTENT_DIRS = ["posts", "chatters", "moments"]
SYNC_CONTENT_FILES = [
    "data/albums.ts", "data/friends.ts", "data/projects.ts",
    "siteConfig.ts", "app/about/about.md",
]
SYNC_UPLOADS = True  # public/uploads/


def _process_result_tail(proc: subprocess.CompletedProcess, max_len: int = 400) -> str:
    text = (proc.stderr or proc.stdout or "").strip()
    return text[-max_len:] if text else f"exit code {proc.returncode}"


def _run_command(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
    )


def _validate_vps_target(server_ip: str, server_user: str, server_port: str, remote_path: str) -> tuple[bool, str]:
    if not re.fullmatch(r"[A-Za-z0-9._-]+", server_ip or ""):
        return False, "服务器地址只能包含字母、数字、点、下划线和短横线。"
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_-]{0,31}", server_user or ""):
        return False, "SSH 用户名格式不正确。"
    if not re.fullmatch(r"\d{1,5}", server_port or "") or not (1 <= int(server_port) <= 65535):
        return False, "SSH 端口必须是 1-65535 的数字。"
    if not re.fullmatch(r"/[A-Za-z0-9._/\-]*", remote_path or ""):
        return False, "远程项目路径必须是绝对路径，且只能包含字母、数字、点、下划线、短横线和斜杠。"
    if any(part == ".." for part in remote_path.split("/")):
        return False, "远程项目路径不能包含 ..。"
    return True, ""


def _ssh_options(server_port: str) -> list[str]:
    return ["-o", "StrictHostKeyChecking=accept-new", "-p", server_port]


def _scp_options(server_port: str) -> list[str]:
    return ["-o", "StrictHostKeyChecking=accept-new", "-P", server_port]


def _ssh_host(server_user: str, server_ip: str) -> str:
    return f"{server_user}@{server_ip}"


def _remote_blog_path(remote_project_path: str) -> str:
    return posixpath.join(remote_project_path.rstrip("/"), "ivoblog", "blog")


def _run_remote(server_user: str, server_ip: str, server_port: str, command: str) -> subprocess.CompletedProcess:
    return _run_command(["ssh", *_ssh_options(server_port), _ssh_host(server_user, server_ip), command])


def _prepare_remote_replace_dir(server_user: str, server_ip: str, server_port: str, remote_dir: str) -> subprocess.CompletedProcess:
    parent = posixpath.dirname(remote_dir.rstrip("/"))
    command = f"mkdir -p {shlex.quote(parent)} && rm -rf {shlex.quote(remote_dir)}"
    return _run_remote(server_user, server_ip, server_port, command)


def _ensure_remote_dir(server_user: str, server_ip: str, server_port: str, remote_dir: str) -> subprocess.CompletedProcess:
    return _run_remote(server_user, server_ip, server_port, f"mkdir -p {shlex.quote(remote_dir)}")


def _sync_remote_directory(server_user: str, server_ip: str, server_port: str, local_dir: str, remote_dir: str) -> tuple[bool, str]:
    prep = _prepare_remote_replace_dir(server_user, server_ip, server_port, remote_dir)
    if prep.returncode != 0:
        return False, _process_result_tail(prep)

    remote_parent = posixpath.dirname(remote_dir.rstrip("/"))
    local_arg = os.path.abspath(local_dir)
    target_arg = f"{_ssh_host(server_user, server_ip)}:{remote_parent}/"
    proc = _run_command(["scp", *_scp_options(server_port), "-r", local_arg, target_arg])
    if proc.returncode != 0:
        return False, _process_result_tail(proc)
    return True, ""


def _sync_remote_file(server_user: str, server_ip: str, server_port: str, local_file: str, remote_file: str) -> tuple[bool, str]:
    parent = posixpath.dirname(remote_file)
    prep = _ensure_remote_dir(server_user, server_ip, server_port, parent)
    if prep.returncode != 0:
        return False, _process_result_tail(prep)

    target_arg = f"{_ssh_host(server_user, server_ip)}:{remote_file}"
    proc = _run_command(["scp", *_scp_options(server_port), os.path.abspath(local_file), target_arg])
    if proc.returncode != 0:
        return False, _process_result_tail(proc)
    return True, ""


def _validate_local_blog_path(blog_path: str) -> str:
    target_root = os.path.realpath(os.path.abspath(blog_path))
    try:
        inside_source_root = os.path.commonpath([SOURCE_ROOT, target_root]) == SOURCE_ROOT
    except ValueError:
        inside_source_root = False
    if inside_source_root:
        raise ValueError("Local Blog path cannot be inside the manager project.")
    if not os.path.isfile(os.path.join(target_root, "package.json")):
        raise ValueError("Local Blog path is not a valid frontend project.")
    return target_root


def _mirror_local_directory(src_dir: str, dst_dir: str) -> None:
    src_real = os.path.realpath(src_dir)
    dst_real = os.path.realpath(dst_dir)
    if src_real == dst_real:
        raise ValueError("Source and target directories are the same.")
    os.makedirs(os.path.dirname(dst_real), exist_ok=True)
    if os.path.exists(dst_real):
        shutil.rmtree(dst_real)
    shutil.copytree(src_real, dst_real)


def _copy_manager_content_to_blog(blog_path: str) -> list[str]:
    blog_root = _validate_local_blog_path(blog_path)
    copied: list[str] = []
    for dirname in SYNC_CONTENT_DIRS:
        src_dir = safe_join(PROJECT_ROOT, dirname)
        dst_dir = safe_join(blog_root, dirname)
        if os.path.isdir(src_dir):
            _mirror_local_directory(src_dir, dst_dir)
            copied.append(f"{dirname}/")

    for rel_path in SYNC_CONTENT_FILES:
        local_rel_path = rel_path.replace("/", os.sep)
        src_file = safe_join(PROJECT_ROOT, local_rel_path)
        dst_file = safe_join(blog_root, local_rel_path)
        if os.path.isfile(src_file):
            os.makedirs(os.path.dirname(dst_file), exist_ok=True)
            shutil.copy2(src_file, dst_file)
            copied.append(rel_path)

    src_uploads = safe_join(PROJECT_ROOT, "public", "uploads")
    dst_uploads = safe_join(blog_root, "public", "uploads")
    if SYNC_UPLOADS and os.path.isdir(src_uploads):
        _mirror_local_directory(src_uploads, dst_uploads)
        copied.append("public/uploads/")

    return copied


def _read_vps_config() -> dict:
    if os.path.exists(VPS_CONFIG_FILE):
        try:
            with open(VPS_CONFIG_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except:
            pass
    return {
        "blogPath": "",
        "serverIp": "",
        "serverUser": "root",
        "serverPort": "22",
        "remoteProjectPath": "/opt/ivoblog",
        "autoRestart": True,
    }


@router.get("/vps/config")
async def get_vps_config():
    return {"success": True, **(_read_vps_config())}


@router.post("/vps/config")
async def save_vps_config(request: Request):
    try:
        data = await request.json()
        os.makedirs(os.path.dirname(VPS_CONFIG_FILE), exist_ok=True)
        atomic_write_json(VPS_CONFIG_FILE, data)
        return {"success": True, "message": "VPS 配置已保存！"}
    except Exception as e:
        return {"success": False, "message": f"保存失败: {str(e)}"}


@router.post("/vps/deploy")
async def deploy_to_vps(request: Request):
    """一键将管理器内容同步到云服务器 Docker 博客"""
    try:
        payload = await request.json()
        vps_config = payload.get("vpsConfig", {})
        blog_path = (payload.get("blogPath", "") or vps_config.get("blogPath", "")).strip()

        server_ip = vps_config.get("serverIp", "").strip()
        server_user = vps_config.get("serverUser", "root").strip()
        server_port = vps_config.get("serverPort", "22").strip()
        remote_path = vps_config.get("remoteProjectPath", "/opt/ivoblog").strip()
        auto_restart = vps_config.get("autoRestart", True)

        if not server_ip:
            return {"success": False, "message": "VPS IP 地址未配置！"}
        valid, validation_message = _validate_vps_target(server_ip, server_user, server_port, remote_path)
        if not valid:
            return {"success": False, "message": validation_message}

        if not blog_path or not os.path.exists(blog_path):
            return {"success": False, "message": "本地 Blog 路径不存在！"}

        local_copied = _copy_manager_content_to_blog(blog_path)
        remote_blog = _remote_blog_path(remote_path)

        init_remote = _ensure_remote_dir(server_user, server_ip, server_port, remote_blog)
        if init_remote.returncode != 0:
            return {"success": False, "message": f"远程目录初始化失败: {_process_result_tail(init_remote)}"}

        results = ["本地管理端内容已同步到 Blog 目录"]
        if local_copied:
            results.append("本地同步清单: " + ", ".join(local_copied))
        errors = []

        # Step 1: Sync content directories (posts, chatters, moments)
        for dirname in SYNC_CONTENT_DIRS:
            local_dir = os.path.join(blog_path, dirname)
            if not os.path.exists(local_dir):
                continue
            ok, err = _sync_remote_directory(
                server_user,
                server_ip,
                server_port,
                local_dir,
                posixpath.join(remote_blog, dirname),
            )
            if ok:
                results.append(f"{dirname}/ 已精准同步")
            else:
                errors.append(f"{dirname}/ 同步失败: {err}")

        # Step 2: Sync individual config/data files
        for rel_path in SYNC_CONTENT_FILES:
            local_file = os.path.join(blog_path, rel_path.replace("/", os.sep))
            if not os.path.exists(local_file):
                continue
            remote_file = posixpath.join(remote_blog, rel_path.replace("\\", "/"))
            ok, err = _sync_remote_file(server_user, server_ip, server_port, local_file, remote_file)
            if ok:
                results.append(f"{rel_path} 已同步")
            else:
                errors.append(f"{rel_path} 同步失败: {err}")

        # Step 3: Sync public/uploads/ if it exists
        local_uploads = os.path.join(blog_path, "public", "uploads")
        if SYNC_UPLOADS and os.path.exists(local_uploads):
            ok, err = _sync_remote_directory(
                server_user,
                server_ip,
                server_port,
                local_uploads,
                posixpath.join(remote_blog, "public", "uploads"),
            )
            if ok:
                results.append("public/uploads/ 已精准同步")
            else:
                errors.append(f"public/uploads/ 同步失败: {err}")

        # Step 4: Restart blog container
        if auto_restart:
            restart_cmd = f"cd {shlex.quote(posixpath.join(remote_path, 'deploy'))} && docker compose restart blog"
            proc = _run_remote(server_user, server_ip, server_port, restart_cmd)
            if proc.returncode == 0:
                results.append("blog 容器已重启，动态页面会读取最新内容")
            else:
                errors.append(f"容器重启失败: {_process_result_tail(proc)}")

        success = len(errors) == 0
        summary = "\n".join(results + errors)
        return {"success": success, "message": summary}

    except Exception as e:
        return {"success": False, "message": f"VPS 部署异常: {str(e)}"}
